/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#131317",
        "surface": "#131317",
        "surface-dim": "#131317",
        "surface-bright": "#39393d",
        "surface-container-lowest": "#0e0e12",
        "surface-container-low": "#1b1b1f",
        "surface-container": "#1f1f24",
        "surface-container-high": "#2a292e",
        "surface-container-highest": "#353439",
        "surface-variant": "#353439",
        "surface-tint": "#bdc2ff",
        "on-background": "#e4e1e7",
        "on-surface": "#e4e1e7",
        "on-surface-variant": "#c7c4d7",
        "primary": "#bdc2ff",
        "primary-fixed": "#e0e0ff",
        "primary-fixed-dim": "#bdc2ff",
        "primary-container": "#7c87f3",
        "on-primary": "#131e8c",
        "on-primary-fixed": "#000767",
        "on-primary-fixed-variant": "#2f3aa3",
        "on-primary-container": "#081486",
        "inverse-primary": "#4953bc",
        "secondary": "#ddb7ff",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#ddb7ff",
        "secondary-container": "#6f00be",
        "on-secondary": "#490080",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        "on-secondary-container": "#d6a9ff",
        "tertiary": "#ffb0cd",
        "tertiary-fixed": "#ffd9e4",
        "tertiary-fixed-dim": "#ffb0cd",
        "tertiary-container": "#f751a1",
        "on-tertiary": "#640039",
        "on-tertiary-fixed": "#3e0022",
        "on-tertiary-fixed-variant": "#8c0053",
        "on-tertiary-container": "#570032",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#908fa0",
        "outline-variant": "#464554",
        "inverse-surface": "#e4e1e7",
        "inverse-on-surface": "#303034",
      },
      fontFamily: {
        "headline": ["Barlow Condensed", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
};
